# Generated by Django 3.2 on 2023-10-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Malin adin yaz.', verbose_name='Malin adi.')),
                ('price', models.FloatField(help_text='Malin sifarish qiymetin yaz.', verbose_name='Malin sifarish qiymeti.')),
                ('price_in_town', models.FloatField(blank=True, help_text='Malin Bakidaki qiymetin yaz. Bilmirsense bosh burax!', verbose_name='Malin Bakidaki qiymeti.')),
                ('cargo_price', models.FloatField(help_text='Malin kargo qiymetin yaz.', verbose_name='Malin kargo qiymeti.')),
                ('additional_cost', models.TextField(blank=True, help_text='Malin eger elave xerci olacagsa, misal ucun airbag fln yaza bilersen. Yoxdursa bosh burax!', verbose_name='Malin elave xercleri.')),
                ('image', models.ImageField(help_text='Malin şəkili varsa yukle. Yoxdursa bosh burax!', upload_to='car_parts', verbose_name='Malin şəkili.')),
            ],
            options={
                'verbose_name': 'Ehtiyat hissesi',
                'verbose_name_plural': 'Ehtiyat hisseleri',
                'ordering': ('name',),
            },
        ),
    ]
