# Generated by Django 3.2 on 2023-10-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_parts', '0003_carparts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Ehtiyat hissesinin mashin markasin adin yaz.', verbose_name='Ehtiyat hissesinin mashin markasi')),
            ],
            options={
                'verbose_name': 'Ehtiyat hissesinin mashin markasi',
                'verbose_name_plural': 'Ehtiyat hisselerin mashin markasi',
                'ordering': ('name',),
            },
        ),
    ]
