# Generated by Django 3.2 on 2023-10-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_parts', '0007_auto_20231024_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='part',
            field=models.CharField(choices=[('Spoiler', 'Spoiler'), ('LED işıq', 'LED işıq'), ('Təkər', 'Təkər'), ('Dırnaq', 'Dırnaq'), ('Ayrıqca', 'Ayrıqca'), ('Stop lampa', 'Stop lampa'), ('Aydınlatma', 'Aydınlatma'), ('Motor', 'Motor'), ('Suspension', 'Suspension'), ('Qapı', 'Qapı'), ('Pəncərə', 'Pəncərə'), ('Yan pəncərə', 'Yan pəncərə'), ('Bağaj', 'Bağaj'), ('Stabilizator çubuğu', 'Stabilizator çubuğu'), ('Yağmağı', 'Yağmağı'), ('Süspension', 'Süspension'), ('Tormoz', 'Tormoz'), ('Şaquliq', 'Şaquliq'), ('Yastıq', 'Yastıq'), ('Elektrika', 'Elektrika'), ('İnteriör', 'İnteriör'), ('Təmizlənmə', 'Təmizlənmə'), ('Yağ', 'Yağ'), ('Dəmir', 'Dəmir'), ('Plastik', 'Plastik'), ('Hərəkət', 'Hərəkət'), ('Zincir', 'Zincir'), ('Ağır qışıq', 'Ağır qışıq'), ('Hava filtri', 'Hava filtri'), ('Elektrik sistemi', 'Elektrik sistemi'), ('Dəmir əşyalar', 'Dəmir əşyalar'), ('Süspension parçaları', 'Süspension parçaları'), ('Qapı hissələri', 'Qapı hissələri'), ('Zəngər', 'Zəngər'), ('Difuzor', 'Difuzor'), ('İskarpin', 'İskarpin'), ('Avtomobil yastıqları', 'Avtomobil yastıqları'), ('Təzələmə', 'Təzələmə'), ('Yağ çatmaq', 'Yağ çatmaq'), ('Yan qapı', 'Yan qapı'), ('Çubuq', 'Çubuq'), ('Difuzor', 'Difuzor'), ('İskarpin', 'İskarpin'), ('Avtomobil yastıqları', 'Avtomobil yastıqları'), ('Təzələmə', 'Təzələmə'), ('Yağ çatmaq', 'Yağ çatmaq'), ('Yan qapı', 'Yan qapı'), ('Çubuq', 'Çubuq'), ('Vəziyyət', 'Vəziyyət'), ('Qapi elceyi', 'Qapi elceyi')], default=None, help_text='Ehtiyat hissesinin kategoriasin seç.', max_length=250, verbose_name='Ehtiyat hissesinin kategoriasi.'),
            preserve_default=False,
        ),
    ]
