# Generated by Django 3.2 on 2023-10-23 23:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_parts', '0009_auto_20231024_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='color',
            field=colorfield.fields.ColorField(default='#0000', help_text='Malin rengin sec.', image_field=None, max_length=25, samples=None, verbose_name='Malin rengi.'),
        ),
    ]
