# Generated by Django 3.2 on 2023-10-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_parts', '0002_auto_20231023_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Ehtiyat hissesinin adin yaz.', verbose_name='Ehtiyat hissesinin adi.')),
            ],
            options={
                'verbose_name': 'Ehtiyat hissesi',
                'verbose_name_plural': 'Ehtiyat hisseleri',
                'ordering': ('name',),
            },
        ),
    ]
