# Generated by Django 3.2 on 2023-10-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_parts', '0004_carbrands'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='brand',
            field=models.ForeignKey(help_text='Ehtiyat hissesinin mashin markasinin kategoriasin seç.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_brand', to='car_parts.carbrands', verbose_name='Ehtiyat hissesinin mashin markasin kategoriasi.'),
        ),
        migrations.AddField(
            model_name='orders',
            name='part',
            field=models.ForeignKey(help_text='Ehtiyat hissesinin kategoriasin seç.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_part', to='car_parts.carparts', verbose_name='Ehtiyat hissesinin kategoriasi.'),
        ),
    ]
