# Generated by Django 3.2 on 2023-10-23 22:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_parts', '0005_auto_20231023_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='color',
            field=colorfield.fields.ColorField(default='#0000', image_field=None, max_length=25, samples=None),
        ),
    ]
